# Check S3 'sparcs-newara' bucket for the complete file
version: '3'

services:
  api:
    container_name: newara
    image: newara:dev
    tty: false
    depends_on:
      - db
    ports:
      - 9000:9000
    environment:
      - DJANGO_ENV=development
      - SECRET_KEY=
      - AWS_BUCKET_NAME=sparcs-kaist-ara-beta
      - AWS_BUCKET_NAME_STATIC=sparcs-kaist-ara-beta-static
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - SSO_CLIENT_ID=
      - SSO_SECRET_KEY=
      - NEWARA_DB_HOST=db
      - NEWARA_DB_PORT=3306
      - NEWARA_DB_USER=root
      - NEWARA_DB_PASSWORD=root-password
      - NEWARA_DB_NAME=new_ara
    entrypoint: /newara/www/entrypoint.sh

  db:
    container_name: db
    image: mysql:5.7
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=new_ara
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
