# Generated by Django 2.2.7 on 2019-11-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190920_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '유저 프로필', 'verbose_name_plural': '유저 프로필 목록'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=128, unique=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sid',
            field=models.CharField(default=None, editable=False, max_length=30, null=True, unique=True, verbose_name='Sparcs SSO sid'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(default=None, editable=False, max_length=30, null=True, unique=True, verbose_name='Sparcs SSO uid'),
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
    ]
