# Generated by Django 2.2.7 on 2019-11-06 03:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20190926_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '문서', 'verbose_name_plural': '문서 목록'},
        ),
        migrations.AlterModelOptions(
            name='articledeletelog',
            options={'verbose_name': '게시물 삭제 기록', 'verbose_name_plural': '게시물 삭제 기록 목록'},
        ),
        migrations.AlterModelOptions(
            name='articlereadlog',
            options={'verbose_name': '게시물 조회 기록', 'verbose_name_plural': '게시물 조회 기록 목록'},
        ),
        migrations.AlterModelOptions(
            name='articleupdatelog',
            options={'verbose_name': '게시물 변경 기록', 'verbose_name_plural': '게시물 변경 기록 목록'},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': '첨부파일', 'verbose_name_plural': '첨부파일 목록'},
        ),
        migrations.AlterModelOptions(
            name='bestarticle',
            options={'verbose_name': '베스트 문서', 'verbose_name_plural': '베스트 문서 목록'},
        ),
        migrations.AlterModelOptions(
            name='bestcomment',
            options={'verbose_name': '베스트 댓글', 'verbose_name_plural': '베스트 댓글 목록'},
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': '차단', 'verbose_name_plural': '차단 목록'},
        ),
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '게시판', 'verbose_name_plural': '게시판 목록'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '댓글', 'verbose_name_plural': '댓글 목록'},
        ),
        migrations.AlterModelOptions(
            name='commentdeletelog',
            options={'verbose_name': '댓글 삭제 기록', 'verbose_name_plural': '댓글 삭제 기록 목록'},
        ),
        migrations.AlterModelOptions(
            name='commentupdatelog',
            options={'verbose_name': '댓글 변경 기록', 'verbose_name_plural': '댓글 변경 기록 목록'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '알림', 'verbose_name_plural': '알림 목록'},
        ),
        migrations.AlterModelOptions(
            name='notificationreadlog',
            options={'verbose_name': '알림 조회 기록', 'verbose_name_plural': '알림 조회 기록 목록'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': '신고', 'verbose_name_plural': '신고 목록'},
        ),
        migrations.AlterModelOptions(
            name='scrap',
            options={'verbose_name': '스크랩', 'verbose_name_plural': '스크랩 목록'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': '말머리', 'verbose_name_plural': '말머리 목록'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': '투표', 'verbose_name_plural': '투표 목록'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='articledeletelog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='articledeletelog',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='articledeletelog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='articlereadlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='articlereadlog',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='articlereadlog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='articleupdatelog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='articleupdatelog',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='articleupdatelog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='bestarticle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bestarticle',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='bestarticle',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='bestcomment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bestcomment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='bestcomment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='block',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='block',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='block',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='commentdeletelog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='commentdeletelog',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='commentdeletelog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='commentupdatelog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='commentupdatelog',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='commentupdatelog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='board',
            name='en_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='게시판 영문 이름'),
        ),
        migrations.AlterField(
            model_name='board',
            name='ko_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='게시판 국문 이름'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='en_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='말머리 영문 이름'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='ko_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='말머리 국문 이름'),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='notificationreadlog',
            unique_together={('read_by', 'notification')},
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('parent_comment', 'reported_by'), ('parent_article', 'reported_by')},
        ),
        migrations.AlterUniqueTogether(
            name='scrap',
            unique_together={('parent_article', 'scrapped_by')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('parent_comment', 'voted_by'), ('parent_article', 'voted_by')},
        ),
        migrations.RemoveField(
            model_name='board',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='board',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='board',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notificationreadlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notificationreadlog',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='notificationreadlog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='updated_at',
        ),
    ]
